import ipaddress
import pathlib
import urllib.request

APNIC_DELEGATED = "https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest"
OUT = pathlib.Path(__file__).resolve().parents[1] / "rust/aerion-core/assets/route/geoip/cn.txt"


def cn_networks(text: str):
    for raw in text.splitlines():
        if raw.startswith("#") or not raw.strip():
            continue
        parts = raw.split("|")
        if len(parts) < 7 or parts[0] != "apnic" or parts[1] != "CN" or parts[6] not in {"allocated", "assigned"}:
            continue
        if parts[2] == "ipv4":
            start = ipaddress.IPv4Address(parts[3])
            end = ipaddress.IPv4Address(int(start) + int(parts[4]) - 1)
            yield from ipaddress.summarize_address_range(start, end)
        elif parts[2] == "ipv6":
            yield ipaddress.IPv6Network(f"{parts[3]}/{parts[4]}", strict=False)


text = urllib.request.urlopen(APNIC_DELEGATED, timeout=30).read().decode("utf-8")
networks = sorted(set(cn_networks(text)), key=lambda item: (item.version, int(item.network_address), item.prefixlen))
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "\n".join(
        [
            "# CN GEOIP route set for Aerion/Mihomo routing.",
            f"# Source: APNIC delegated-apnic-latest ({APNIC_DELEGATED})",
            "# Generated by scripts/update-route-assets.py.",
            *[str(item) for item in networks],
        ]
    )
    + "\n",
    encoding="utf-8",
)
print(f"wrote {OUT} ({len(networks)} CIDR lines)")
